### ISSUE TITLE
zipline example algo's fail on "JSONDecodeError"  using docker image

### ISSUE THREAD

**Issue by JOravetz** [alpacahq/alpaca-zipline#3]
Hi,

I successfully built the docker image and ingested the alpaca-bundle, as described in the documentation.  

zipline ingest -b alpaca-bundle
Downloading Bundle: alpaca-bundle  [####################################]  100%          
Writing data to /root/.zipline/data/alpaca-bundle/2019-07-08T07;05;52.204324.

When running an example algorithm, however, I always get a json.decoder error (see below).  Is this error coming from the ingested bundle or something different with regards to recent zipline issues?  Please let me know if you are able to reproduce the error.

(using bash shell in alpaca-zipline docker image):

zipline run -f /work/examples/dual_moving_average.py --broker=alpaca --broker-uri=dummy --state-file /work/state --realtime-bar-target /work/realtime-bars --bundle alpaca-bundle --data-frequency daily --start 2015-1-1 --end 2016-1-1

2019-07-08 07:30:21.428332] INFO: Loader: Cache at /root/.zipline/data/SPY_benchmark.csv does not have data from 1990-01-02 00:00:00+00:00 to 2019-07-03 00:00:00+00:00.

[2019-07-08 07:30:21.428517] INFO: Loader: Downloading benchmark data for 'SPY'.
Traceback (most recent call last):
  File "/usr/local/bin/zipline", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/zipline/__main__.py", line 102, in _
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/zipline/__main__.py", line 316, in run
    realtime_bar_target=realtime_bar_target
  File "/usr/local/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 142, in _run
    env = TradingEnvironment(asset_db_path=connstr, environ=environ)
  File "/usr/local/lib/python3.5/site-packages/zipline/finance/trading.py", line 99, in __init__
    self.bm_symbol,
  File "/usr/local/lib/python3.5/site-packages/zipline/data/loader.py", line 165, in load_market_data
    environ,
  File "/usr/local/lib/python3.5/site-packages/zipline/data/loader.py", line 215, in ensure_benchmark_data
    data = get_benchmark_returns(symbol)
  File "/usr/local/lib/python3.5/site-packages/zipline/data/benchmarks.py", line 36, in get_benchmark_returns
    data = json.loads(r.text)
  File "/usr/local/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks very much for your attention to this.  I would very much like to get zipline properly setup to continue porting my algorithms into Alpaca's trading platform.

Regards,

Joseph Oravetz

**Comment by BambooFlower** [comment]
Did you manage to solve the issue? I am having the same problem

**Comment by JOravetz** [comment]
Hi sorry - haven’t worked on the problem recently or found a solution .  Please let me know if u find something .  

Regards,

Joe O

**Comment by veekon** [comment]
https://github.com/quantopian/zipline/issues/2480 problem is this but implementing the fix from docker will be a bit of a pain
